### ISSUE TITLE
Arregla la web desgraciao

### ISSUE THREAD

**Issue by PaquitoelChocolatero** [guluc3m/newGULpage#2]
-Meter una pestaña de eventos (Jornadas, GUL Jamón)
-Poner el horario/calendario en la pestaña de cada grupo
-Usar OpenStreetView
-Mantener el matrix

**Comment by metroid2010** [comment]
Lo del matrix está muy visto. No engañamos a nadie con el rollo `1337 h4x0r`
Lo del OpenStreetView sí que deberíamos hacerlo, por mantener el compromiso con el software libre. Además, funciona bien.
Para el horario, lo suyo sería buscar un plugin WebCal, para no hacer modificaciones en el código html cada vez que algo cambie.
Sobre los eventos, ahora mismo está parada la cosa, así que no urge especialmente

**Comment by PaquitoelChocolatero** [comment]
Peroo lo de matrix es bonito
La página de la GUL Jamón a parte de información del evento (que no cambia) tiene los juegos ganadores por si alguien los quiere probar, no es tan complicado hacer la pestaña

**Comment by Jorgeelalto** [comment]
lo de openstreetview ya está arreglado para el próximo commit

**Comment by metroid2010** [comment]
Sobre la página para la Gul Jamón, sí, eso parece guay. Unos snippets de código, y unos links a las repos. Alguna fotillo también

**Comment by PaquitoelChocolatero** [comment]
Está chachi lo de los iconitos, pero te dejas la pestaña de la radio, que ya tiene página, sólo tienes que redirigir a ella

**Comment by Jorgeelalto** [comment]
El link a radio ya funciona, pero no estoy seguro de si hacer un boton extra para eso (con un drop down o algo) o poner un resumen de eventos al final de index (y cuando funcionen los media queries y las cajas se redimensionen correctamente quedara bien)

**Comment by PaquitoelChocolatero** [comment]
Yo creo que como está queda bien
Pd: falta la GUL Jamón

**Comment by PaquitoelChocolatero** [comment]
En contacto yo añadiría info-list@gul.uc3m.es a demás de las redes sociales (y se podría pensar lo del grupo de telegram público para dudas)

**Comment by PaquitoelChocolatero** [comment]
Hay que convertir los grupos del header en botones para no tener que darle a la palabra

**Comment by Jorgeelalto** [comment]
Como no me pongas mensajes con sentido en los commmits te hackeo la computadora bro @PaquitoelChocolatero

**Comment by Jorgeelalto** [comment]
> Hay que convertir los grupos del header en botones para no tener que darle a la palabra

Hecho

**Comment by PaquitoelChocolatero** [comment]
> 
> 
> Como no me pongas mensajes con sentido en los commmits te hackeo la computadora bro @PaquitoelChocolatero

NUNCA!!

**Comment by PaquitoelChocolatero** [comment]
Habría que investigar como quitar el barrido inicial de matrix porque es to feo

**Comment by Jorgeelalto** [comment]
Tiene muy mala pinta eso, yo la verdad es que no se lo que hace pero con las pocas líneas que hay no me extrañaría que fuera un comportamiento que no buscaban pero que lo tienen. En todas las demos que he visto que son similares a este ocurre lo mismo.

**Comment by Jorgeelalto** [comment]
Hay que ver cómo vamos a dejar los fondos de las páginas de los grupos de trabajo. Ahora mismo están en gris blanco, pero así es como teníamos el index antes y se dijo que era muy soso. A mi se me ha ocurrido poner el efecto matrix pero siguiendo el esquema de colores de cada cosa (En Android el verde de Android y blanco, por ejemplo; en Hack3rs el rojo de Hackers y el blanco; en Arduino el azul verdoso y el negro...) pero igual es demasiado empalagoso porque tendríamos efecto matrix en todas las páginas... Qué os parece?

**Comment by PaquitoelChocolatero** [comment]
Pero por ejemplo en la página antigua no sale (o no se ve).
Hmm así a priori el matrix está bien y por encima podemos distribuir contenido asi:
![sin titulo](https://user-images.githubusercontent.com/33132109/46905312-197f9800-cef2-11e8-8a2e-6846bc81a4e3.png)
Por cierto, podemos mirar lo de hacer un desplegable para la versión móvil, que no parece muy complicado (parece...)

**Comment by d-marcos-m** [comment]
> Habría que investigar como quitar el barrido inicial de matrix porque es to feo

Arreglado en https://github.com/guluc3m/newGULpage/commit/defeecd0791391a14b87b0cb98711db9414a48be

Básicamente había que cambiar el punto de inicio de cada columna de 0 a 100, para que al entrar en la función draw ya "matase" todas y las iniciase de nuevo o no según el random que tiene. Al estar a 0, no mataba a ninguna hasta que llegasen al final.

**Comment by Jorgeelalto** [comment]
Voy a cerrar el issue porque ha quedado un poco generalista y creo que con lo que llevamos hecho vale.

Para los siguientes estaría bien tener un issue por cada problema (siempre que sea suficientemente complejo). @PaquitoelChocolatero 

PD: Muchas gracias y bienvenido @dmarcosm , me alegro de que estés por aquí
