### ISSUE TITLE
Mover esta repo a la cuenta del GUL

### ISSUE THREAD

**Issue by metroid2010** [guluc3m/newGULpage#4]
Ya que nos ponemos en serio, vamos a hacerlo bien.
Deberíamos:
- Trasladar esta repo a la cuenta del gul (@guluc3m)
- Meter a los nuevos miembros en esta organización (como yo, por ejemplo)
- Asignar otro administrador para la organización, uno que esté activo en el Gul irl
- (opcional) Crear proyectos para cada uno de los grupos de trabajo, y mover las cosas desde aquí

**Comment by PaquitoelChocolatero** [comment]
Ya hay repo para todos los grupos "antiguos", de los nuevos no hay nada porque aún no hemos empezado. Y sí, habría que poner admins nuevos...
